### ISSUE TITLE
all commands fail if ~/starling isn't your pwd

### ISSUE THREAD

**Issue by finoradin** [filecoin-project/starling#24]
Not sure if this is just how our current test environment was set up, but currently all commands fail if you try and run any `starling` commands when `~/starling` isn't your present working directory.

**Comment by alexandrumatei36** [comment]
@finoradin should work now. Please check again and close the issue if commands don't fail anymore

**Comment by finoradin** [comment]
Still doesn't work.

Steps to reproduce: 
1. ssh into the server
2. run `starling monitor`

result is: 

```
(node:24736) UnhandledPromiseRejectionWarning: Error: Invalid URL: undefined
    at WebSocket.initAsClient (/home/paperspace/starling/node_modules/ws/lib/websocket.js:455:11)
    at new WebSocket (/home/paperspace/starling/node_modules/ws/lib/websocket.js:62:20)
    at Client._default [as webSocketFactory] (/home/paperspace/starling/node_modules/rpc-websockets/dist/lib/client/websocket.js:21:10)
    at Client._connect (/home/paperspace/starling/node_modules/rpc-websockets/dist/lib/client.js:391:26)
    at new CommonClient (/home/paperspace/starling/node_modules/rpc-websockets/dist/lib/client.js:89:34)
    at Client._createSuperInternal (/home/paperspace/starling/node_modules/rpc-websockets/dist/index.js:30:317)
    at new Client (/home/paperspace/starling/node_modules/rpc-websockets/dist/index.js:70:19)
    at new LotusWsClient (/home/paperspace/starling/core/infrastructure/lotus/LotusWsClient.js:12:19)
    at Function.shared (/home/paperspace/starling/core/infrastructure/lotus/LotusWsClient.js:30:23)
    at monitor (/home/paperspace/starling/commands/monitor/monitor.js:124:32)
    at Command.<anonymous> (/home/paperspace/starling/index.js:60:9)
    at Command.listener (/home/paperspace/starling/node_modules/commander/index.js:291:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (/home/paperspace/starling/node_modules/commander/index.js:672:12)
    at Command.parse (/home/paperspace/starling/node_modules/commander/index.js:459:21)
    at init (/home/paperspace/starling/index.js:103:13)
(node:24736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

3. `cd ~/starling`
4. `starling monitor`
5. now it works…

**Comment by finoradin** [comment]
Working now
